export enum NotificationType {
  FOLLOW = 'FOLLOW',
  DOWNLOAD_TRACK = 'DOWNLOAD_TRACK',
  LIKE_TRACK = 'LIKE_TRACK',
  SAVE_PLAYLIST = 'SAVE_PLAYLIST',
  SAVE_ALBUM = 'SAVE_ALBUM',
  COLLABORATE_PLAYLIST = 'COLLABORATE_PLAYLIST',
  NEW_TRACK = 'NEW_TRACK',
  NEW_ALBUM = 'NEW_ALBUM',
  NEW_PLAYLIST = 'NEW_PLAYLIST',
}
